2023-05-28 02:03:35,899 - INFO - add_to_cart method called
2023-05-28 02:03:35,900 - INFO - checking if table exist!!...
2023-05-28 02:03:35,921 - INFO - session closed
2023-05-28 02:03:35,922 - ERROR - key error list index out of range
2023-05-28 02:03:35,922 - INFO - item not present in cart 
2023-05-28 02:03:35,922 - INFO - checking if table exist!!...
2023-05-28 02:03:35,937 - ERROR - Error: connection issue (pymysql.err.OperationalError) (1054, "Unknown column 'item_id' in 'where clause'")
[SQL: SELECT count from item where item_id='c122';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-05-28 02:03:36,989 - ERROR - Error: connection issue (pymysql.err.OperationalError) (1054, "Unknown column 'item_id' in 'where clause'")
[SQL: SELECT count from item where item_id='c122';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-05-28 02:03:38,054 - ERROR - Error: connection issue (pymysql.err.OperationalError) (1054, "Unknown column 'item_id' in 'where clause'")
[SQL: SELECT count from item where item_id='c122';]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-05-28 02:03:39,056 - ERROR - Could not perform database eration after 3 retries
2023-05-28 02:03:39,056 - INFO - Validation time: 0.000 seconds
2023-05-28 02:03:39,056 - INFO - Execution time: 3.156 seconds
2023-05-28 02:03:39,057 - ERROR - Exception on /add_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:07:53,700 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:08:14,338 - INFO - Validation time: 2.147 seconds
2023-05-28 02:08:14,339 - INFO - add_to_cart method called
2023-05-28 02:08:14,339 - INFO - checking if table exist!!...
2023-05-28 02:08:14,410 - INFO - session closed
2023-05-28 02:08:14,410 - ERROR - key error list index out of range
2023-05-28 02:08:14,410 - INFO - item not present in cart 
2023-05-28 02:08:14,410 - INFO - checking if table exist!!...
2023-05-28 02:08:14,824 - INFO - session closed
2023-05-28 02:08:14,825 - INFO - checking if table exist!!...
2023-05-28 02:08:17,636 - INFO - row inserted!..
2023-05-28 02:08:17,660 - INFO - session closed
2023-05-28 02:08:17,660 - INFO - Validation time: 2.148 seconds
2023-05-28 02:08:17,660 - INFO - Execution time: 5.470 seconds
2023-05-28 02:09:39,959 - INFO - Validation time: 0.131 seconds
2023-05-28 02:09:39,970 - INFO - show cart  function triggered!...
2023-05-28 02:09:39,971 - INFO - checking if table exist!!...
2023-05-28 02:09:40,061 - INFO - session closed
2023-05-28 02:09:40,075 - INFO - Validation time: 0.142 seconds
2023-05-28 02:09:40,075 - INFO - Execution time: 0.253 seconds
2023-05-28 02:18:01,611 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:18:20,658 - INFO - Validation time: 2.226 seconds
2023-05-28 02:18:20,672 - INFO - add_to_cart method called
2023-05-28 02:18:20,673 - INFO - checking if table exist!!...
2023-05-28 02:18:21,325 - INFO - session closed
2023-05-28 02:18:21,326 - ERROR - key error list index out of range
2023-05-28 02:18:21,326 - INFO - item not present in cart 
2023-05-28 02:18:21,327 - INFO - checking if table exist!!...
2023-05-28 02:18:21,357 - INFO - session closed
2023-05-28 02:18:21,358 - INFO - checking if table exist!!...
2023-05-28 02:18:21,412 - INFO - row inserted!..
2023-05-28 02:18:21,434 - INFO - session closed
2023-05-28 02:18:21,434 - INFO - Validation time: 2.234 seconds
2023-05-28 02:18:21,434 - INFO - Execution time: 3.005 seconds
2023-05-28 02:19:25,194 - INFO - Validation time: 0.226 seconds
2023-05-28 02:19:25,208 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-05-28 02:19:25,209 - INFO - Validation time: 0.243 seconds
2023-05-28 02:19:25,209 - INFO - Execution time: 0.248 seconds
2023-05-28 02:19:25,218 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:23:12,683 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:23:26,024 - INFO - Validation time: 2.214 seconds
2023-05-28 02:23:26,025 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-05-28 02:23:26,025 - INFO - Validation time: 2.215 seconds
2023-05-28 02:23:26,025 - INFO - Execution time: 2.215 seconds
2023-05-28 02:23:26,026 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:27:22,810 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:27:40,297 - INFO - Validation time: 6.921 seconds
2023-05-28 02:28:20,021 - INFO - Validation time: 0.039 seconds
2023-05-28 02:28:20,043 - INFO - show cart  function triggered!...
2023-05-28 02:28:20,045 - INFO - checking if table exist!!...
2023-05-28 02:28:20,167 - INFO - session closed
2023-05-28 02:28:20,173 - INFO - Validation time: 0.049 seconds
2023-05-28 02:28:20,173 - INFO - Execution time: 0.194 seconds
2023-05-28 02:29:25,204 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:29:42,758 - INFO - Validation time: 2.160 seconds
2023-05-28 02:29:42,763 - INFO - show cart  function triggered!...
2023-05-28 02:29:42,763 - INFO - checking if table exist!!...
2023-05-28 02:29:42,949 - INFO - session closed
2023-05-28 02:29:42,950 - INFO - Validation time: 2.164 seconds
2023-05-28 02:29:42,950 - INFO - Execution time: 2.355 seconds
2023-05-28 02:30:50,353 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:31:02,770 - INFO - Validation time: 2.109 seconds
2023-05-28 02:31:02,772 - INFO - show cart  function triggered!...
2023-05-28 02:31:02,772 - INFO - checking if table exist!!...
2023-05-28 02:31:02,821 - INFO - session closed
2023-05-28 02:31:02,821 - ERROR - An exception occurred:list index out of range
2023-05-28 02:31:02,821 - ERROR - list index out of range
2023-05-28 02:31:02,821 - INFO - Validation time: 2.111 seconds
2023-05-28 02:31:02,821 - INFO - Execution time: 2.160 seconds
2023-05-28 02:31:02,822 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:34:33,110 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:34:46,073 - INFO - Validation time: 2.190 seconds
2023-05-28 02:34:46,076 - INFO - show cart  function triggered!...
2023-05-28 02:34:46,076 - INFO - checking if table exist!!...
2023-05-28 02:34:46,133 - INFO - session closed
2023-05-28 02:34:46,133 - ERROR - An exception occurred:list index out of range
2023-05-28 02:34:46,133 - ERROR - list index out of range
2023-05-28 02:34:46,133 - INFO - Validation time: 2.192 seconds
2023-05-28 02:34:46,133 - INFO - Execution time: 2.250 seconds
2023-05-28 02:34:46,134 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:41:24,775 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:41:40,980 - INFO - Validation time: 2.178 seconds
2023-05-28 02:41:40,985 - INFO - show cart  function triggered!...
2023-05-28 02:41:40,986 - INFO - checking if table exist!!...
2023-05-28 02:41:41,286 - INFO - session closed
2023-05-28 02:41:41,286 - ERROR - An exception occurred:list index out of range
2023-05-28 02:41:41,286 - ERROR - list index out of range
2023-05-28 02:41:41,286 - INFO - Validation time: 2.182 seconds
2023-05-28 02:41:41,287 - INFO - Execution time: 2.486 seconds
2023-05-28 02:41:41,287 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:44:23,215 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:44:37,386 - INFO - Validation time: 2.163 seconds
2023-05-28 02:44:37,390 - INFO - show cart  function triggered!...
2023-05-28 02:44:37,390 - INFO - checking if table exist!!...
2023-05-28 02:44:37,513 - INFO - session closed
2023-05-28 02:44:37,514 - ERROR - An exception occurred:list index out of range
2023-05-28 02:44:37,514 - ERROR - list index out of range
2023-05-28 02:44:37,514 - INFO - Validation time: 2.167 seconds
2023-05-28 02:44:37,514 - INFO - Execution time: 2.294 seconds
2023-05-28 02:44:37,515 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:49:57,934 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:50:21,792 - INFO - Validation time: 2.269 seconds
2023-05-28 02:50:21,810 - INFO - show cart  function triggered!...
2023-05-28 02:50:21,811 - INFO - checking if table exist!!...
2023-05-28 02:50:21,930 - INFO - session closed
2023-05-28 02:50:21,931 - ERROR - An exception occurred:list index out of range
2023-05-28 02:50:21,931 - ERROR - list index out of range
2023-05-28 02:50:21,931 - INFO - Validation time: 2.282 seconds
2023-05-28 02:50:21,931 - INFO - Execution time: 2.414 seconds
2023-05-28 02:50:21,935 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:51:26,027 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:51:46,929 - INFO - Validation time: 2.162 seconds
2023-05-28 02:51:46,934 - INFO - show cart  function triggered!...
2023-05-28 02:51:46,935 - INFO - checking if table exist!!...
2023-05-28 02:51:47,007 - INFO - session closed
2023-05-28 02:51:47,007 - ERROR - An exception occurred:list index out of range
2023-05-28 02:51:47,007 - ERROR - list index out of range
2023-05-28 02:51:47,008 - INFO - Validation time: 2.164 seconds
2023-05-28 02:51:47,008 - INFO - Execution time: 2.241 seconds
2023-05-28 02:51:47,008 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 02:55:15,329 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:55:25,396 - INFO - Validation time: 2.240 seconds
2023-05-28 02:55:25,397 - INFO - show cart  function triggered!...
2023-05-28 02:55:25,397 - INFO - checking if table exist!!...
2023-05-28 02:55:25,500 - INFO - session closed
2023-05-28 02:55:25,501 - INFO - Validation time: 2.241 seconds
2023-05-28 02:55:25,501 - INFO - Execution time: 2.346 seconds
2023-05-28 02:58:03,423 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 02:58:16,498 - INFO - Validation time: 2.288 seconds
2023-05-28 02:58:16,507 - INFO - show cart  function triggered!...
2023-05-28 02:58:16,508 - INFO - checking if table exist!!...
2023-05-28 02:58:16,660 - INFO - session closed
2023-05-28 02:58:16,661 - INFO - Validation time: 2.291 seconds
2023-05-28 02:58:16,661 - INFO - Execution time: 2.451 seconds
2023-05-28 03:01:55,377 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:02:08,251 - INFO - Validation time: 2.270 seconds
2023-05-28 03:02:08,265 - INFO - show cart  function triggered!...
2023-05-28 03:02:08,268 - INFO - checking if table exist!!...
2023-05-28 03:02:08,439 - INFO - session closed
2023-05-28 03:02:08,441 - INFO - Validation time: 2.279 seconds
2023-05-28 03:02:08,441 - INFO - Execution time: 2.463 seconds
2023-05-28 03:07:52,346 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:08:15,219 - INFO - Validation time: 2.271 seconds
2023-05-28 03:08:15,228 - INFO - add_to_cart method called
2023-05-28 03:08:15,228 - INFO - checking if table exist!!...
2023-05-28 03:08:15,324 - INFO - session closed
2023-05-28 03:08:15,325 - ERROR - key error list index out of range
2023-05-28 03:08:15,325 - INFO - item not present in cart 
2023-05-28 03:08:15,325 - INFO - checking if table exist!!...
2023-05-28 03:08:15,359 - INFO - session closed
2023-05-28 03:08:15,359 - INFO - checking if table exist!!...
2023-05-28 03:08:15,397 - INFO - row inserted!..
2023-05-28 03:08:15,411 - INFO - session closed
2023-05-28 03:08:15,411 - INFO - Validation time: 2.276 seconds
2023-05-28 03:08:15,411 - INFO - Execution time: 2.465 seconds
2023-05-28 03:08:28,954 - INFO - add_to_cart method called
2023-05-28 03:08:28,957 - INFO - checking if table exist!!...
2023-05-28 03:08:28,999 - INFO - session closed
2023-05-28 03:08:29,000 - ERROR - key error list index out of range
2023-05-28 03:08:29,000 - INFO - item not present in cart 
2023-05-28 03:08:29,000 - INFO - checking if table exist!!...
2023-05-28 03:08:29,016 - INFO - session closed
2023-05-28 03:08:29,017 - INFO - checking if table exist!!...
2023-05-28 03:08:29,030 - INFO - row inserted!..
2023-05-28 03:08:29,220 - INFO - session closed
2023-05-28 03:08:29,221 - INFO - Validation time: 0.002 seconds
2023-05-28 03:08:29,221 - INFO - Execution time: 0.276 seconds
2023-05-28 03:08:46,654 - INFO - show cart  function triggered!...
2023-05-28 03:08:46,659 - INFO - checking if table exist!!...
2023-05-28 03:08:46,777 - INFO - session closed
2023-05-28 03:08:46,779 - ERROR - An exception occurred:list index out of range
2023-05-28 03:08:46,779 - ERROR - list index out of range
2023-05-28 03:08:46,780 - INFO - Validation time: 0.004 seconds
2023-05-28 03:08:46,780 - INFO - Execution time: 0.135 seconds
2023-05-28 03:08:46,789 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:17:54,697 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:18:18,645 - INFO - Validation time: 2.414 seconds
2023-05-28 03:18:18,667 - INFO - show cart  function triggered!...
2023-05-28 03:18:18,670 - INFO - checking if table exist!!...
2023-05-28 03:18:18,811 - INFO - query select * from external.tbl_cart1 where session_id='debyan_dsdsfed' and is_active= 1;
2023-05-28 03:18:18,853 - INFO - session closed
2023-05-28 03:18:18,855 - ERROR - An exception occurred:list index out of range
2023-05-28 03:18:18,855 - ERROR - list index out of range
2023-05-28 03:18:18,856 - INFO - Validation time: 2.436 seconds
2023-05-28 03:18:18,856 - INFO - Execution time: 2.636 seconds
2023-05-28 03:18:18,860 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:19:41,010 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:19:52,657 - INFO - Validation time: 2.255 seconds
2023-05-28 03:19:52,661 - INFO - show cart  function triggered!...
2023-05-28 03:19:52,661 - INFO - checking if table exist!!...
2023-05-28 03:19:52,712 - INFO - query select * from external.tbl_cart1 where session_id='debyan_dsdsfed' and is_active= 1;
2023-05-28 03:19:52,736 - INFO - session closed
2023-05-28 03:19:52,737 - ERROR - An exception occurred:list index out of range
2023-05-28 03:19:52,737 - ERROR - list index out of range
2023-05-28 03:19:52,737 - INFO - Validation time: 2.256 seconds
2023-05-28 03:19:52,737 - INFO - Execution time: 2.335 seconds
2023-05-28 03:19:52,737 - ERROR - Exception on /show_wo_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_wo_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:22:21,662 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:23:01,160 - INFO - Validation time: 2.425 seconds
2023-05-28 03:23:01,197 - INFO - show cart  function triggered!...
2023-05-28 03:23:01,200 - INFO - checking if table exist!!...
2023-05-28 03:23:01,364 - INFO - query select * from external.tbl_cart1 where session_id='debyan_dsdsfed' and is_active= 1;
2023-05-28 03:23:01,420 - INFO - session closed
2023-05-28 03:23:01,431 - INFO - Validation time: 2.447 seconds
2023-05-28 03:23:01,431 - INFO - Execution time: 2.707 seconds
2023-05-28 03:25:44,677 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:26:03,973 - INFO - Validation time: 2.146 seconds
2023-05-28 03:26:03,983 - INFO - show cart  function triggered!...
2023-05-28 03:26:03,983 - INFO - checking if table exist!!...
2023-05-28 03:26:04,032 - INFO - query select * from external.tbl_cart where session_id='debyan_dsdsfed' and is_active= true;
2023-05-28 03:26:04,048 - INFO - session closed
2023-05-28 03:26:04,051 - INFO - Validation time: 2.152 seconds
2023-05-28 03:26:04,051 - INFO - Execution time: 2.228 seconds
2023-05-28 03:29:58,462 - INFO - Validation time: 6.532 seconds
2023-05-28 03:30:49,084 - INFO - Validation time: 0.098 seconds
2023-05-28 03:30:49,098 - INFO - show cart  function triggered!...
2023-05-28 03:30:49,100 - INFO - checking if table exist!!...
2023-05-28 03:30:49,131 - INFO - query select * from external.tbl_cart where session_id='debyan_dsdsfed' and is_active= true;
2023-05-28 03:30:49,145 - INFO - session closed
2023-05-28 03:30:49,149 - INFO - Validation time: 0.109 seconds
2023-05-28 03:30:49,149 - INFO - Execution time: 0.168 seconds
2023-05-28 03:35:07,628 - INFO - Validation time: 2.296 seconds
2023-05-28 03:35:07,644 - ERROR - __init__() missing 1 required positional argument: 'is_active'
2023-05-28 03:35:07,645 - INFO - Validation time: 2.310 seconds
2023-05-28 03:35:07,645 - INFO - Execution time: 2.320 seconds
2023-05-28 03:35:07,649 - ERROR - Exception on /add_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'add_to_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-28 03:36:31,444 - INFO - Serving on http://0.0.0.0:5008
2023-05-28 03:36:47,112 - INFO - Validation time: 2.171 seconds
2023-05-28 03:36:47,116 - INFO - add_to_cart method called
2023-05-28 03:36:47,117 - INFO - checking if table exist!!...
2023-05-28 03:36:47,176 - INFO - session closed
2023-05-28 03:36:47,176 - ERROR - key error list index out of range
2023-05-28 03:36:47,176 - INFO - item not present in cart 
2023-05-28 03:36:47,177 - INFO - checking if table exist!!...
2023-05-28 03:36:47,192 - INFO - session closed
2023-05-28 03:36:47,192 - INFO - checking if table exist!!...
2023-05-28 03:36:47,221 - INFO - row inserted!..
2023-05-28 03:36:47,229 - INFO - session closed
2023-05-28 03:36:47,229 - INFO - Validation time: 2.173 seconds
2023-05-28 03:36:47,230 - INFO - Execution time: 2.288 seconds
2023-05-28 03:37:42,368 - INFO - add_to_cart method called
2023-05-28 03:37:42,369 - INFO - checking if table exist!!...
2023-05-28 03:37:42,387 - INFO - session closed
2023-05-28 03:37:42,388 - INFO - item is already present in cart!! updating..
2023-05-28 03:37:42,388 - INFO - checking if table exist!!...
2023-05-28 03:37:42,398 - INFO - session closed
2023-05-28 03:37:42,399 - INFO - checking if table exist!!...
2023-05-28 03:37:42,407 - INFO - row inserted!..
2023-05-28 03:37:42,417 - INFO - session closed
2023-05-28 03:37:42,418 - INFO - Validation time: 0.000 seconds
2023-05-28 03:37:42,418 - INFO - Execution time: 0.052 seconds
2023-05-28 04:37:15,409 - INFO - Validation time: 2.339 seconds
2023-05-28 04:37:15,422 - INFO - add_to_cart method called
2023-05-28 04:37:15,423 - INFO - checking if table exist!!...
2023-05-28 04:37:15,512 - INFO - session closed
2023-05-28 04:37:15,512 - INFO - item is already present in cart!! updating..
2023-05-28 04:37:15,513 - INFO - checking if table exist!!...
2023-05-28 04:37:15,527 - INFO - session closed
2023-05-28 04:37:15,528 - INFO - checking if table exist!!...
2023-05-28 04:37:15,539 - INFO - row inserted!..
2023-05-28 04:37:15,553 - INFO - session closed
2023-05-28 04:37:15,553 - INFO - Validation time: 2.351 seconds
2023-05-28 04:37:15,554 - INFO - Execution time: 2.487 seconds
2023-05-28 04:37:52,142 - INFO - add_to_cart method called
2023-05-28 04:37:52,149 - INFO - checking if table exist!!...
2023-05-28 04:37:52,215 - INFO - session closed
2023-05-28 04:37:52,215 - INFO - item is already present in cart!! updating..
2023-05-28 04:37:52,216 - INFO - checking if table exist!!...
2023-05-28 04:37:52,230 - INFO - session closed
2023-05-28 04:37:52,230 - INFO - checking if table exist!!...
2023-05-28 04:37:52,272 - INFO - row inserted!..
2023-05-28 04:37:52,283 - INFO - session closed
2023-05-28 04:37:52,285 - INFO - Validation time: 0.008 seconds
2023-05-28 04:37:52,285 - INFO - Execution time: 0.164 seconds
2023-05-28 04:38:03,151 - INFO - add_to_cart method called
2023-05-28 04:38:03,151 - INFO - checking if table exist!!...
2023-05-28 04:38:03,187 - INFO - session closed
2023-05-28 04:38:03,188 - INFO - item is already present in cart!! updating..
2023-05-28 04:38:03,188 - INFO - checking if table exist!!...
2023-05-28 04:38:03,208 - INFO - session closed
2023-05-28 04:38:03,208 - INFO - checking if table exist!!...
2023-05-28 04:38:03,225 - INFO - row inserted!..
2023-05-28 04:38:03,249 - INFO - session closed
2023-05-28 04:38:03,249 - INFO - Validation time: 0.000 seconds
2023-05-28 04:38:03,249 - INFO - Execution time: 0.099 seconds
2023-05-29 08:55:42,936 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 08:56:53,371 - INFO - Validation time: 2.455 seconds
2023-05-29 08:56:53,402 - INFO - add_to_cart method called
2023-05-29 08:56:53,406 - INFO - checking if table exist!!...
2023-05-29 08:56:53,840 - INFO - session closed
2023-05-29 08:56:53,844 - ERROR - key error list index out of range
2023-05-29 08:56:53,844 - INFO - item not present in cart 
2023-05-29 08:56:53,845 - INFO - checking if table exist!!...
2023-05-29 08:56:55,028 - INFO - session closed
2023-05-29 08:56:55,028 - INFO - checking if table exist!!...
2023-05-29 08:56:55,090 - INFO - row inserted!..
2023-05-29 08:56:55,106 - INFO - session closed
2023-05-29 08:56:55,106 - INFO - Validation time: 2.482 seconds
2023-05-29 08:56:55,106 - INFO - Execution time: 4.202 seconds
2023-05-29 08:57:11,756 - INFO - add_to_cart method called
2023-05-29 08:57:11,760 - INFO - checking if table exist!!...
2023-05-29 08:57:11,793 - INFO - session closed
2023-05-29 08:57:11,794 - ERROR - key error list index out of range
2023-05-29 08:57:11,794 - INFO - item not present in cart 
2023-05-29 08:57:11,794 - INFO - checking if table exist!!...
2023-05-29 08:57:11,804 - INFO - session closed
2023-05-29 08:57:11,804 - INFO - checking if table exist!!...
2023-05-29 08:57:11,811 - INFO - row inserted!..
2023-05-29 08:57:11,820 - INFO - session closed
2023-05-29 08:57:11,820 - INFO - Validation time: 0.004 seconds
2023-05-29 08:57:11,820 - INFO - Execution time: 0.077 seconds
2023-05-29 08:59:06,142 - INFO - Validation time: 0.327 seconds
2023-05-29 08:59:06,153 - INFO - add_to_cart method called
2023-05-29 08:59:06,155 - INFO - checking if table exist!!...
2023-05-29 08:59:06,234 - INFO - session closed
2023-05-29 08:59:06,235 - ERROR - key error list index out of range
2023-05-29 08:59:06,235 - INFO - item not present in cart 
2023-05-29 08:59:06,235 - INFO - checking if table exist!!...
2023-05-29 08:59:06,251 - INFO - session closed
2023-05-29 08:59:06,252 - INFO - checking if table exist!!...
2023-05-29 08:59:06,261 - INFO - row inserted!..
2023-05-29 08:59:06,273 - INFO - session closed
2023-05-29 08:59:06,273 - INFO - Validation time: 0.341 seconds
2023-05-29 08:59:06,273 - INFO - Execution time: 0.464 seconds
2023-05-29 08:59:40,759 - INFO - show cart  function triggered!...
2023-05-29 08:59:40,768 - INFO - checking if table exist!!...
2023-05-29 08:59:40,841 - INFO - session closed
2023-05-29 08:59:40,868 - INFO - Validation time: 0.003 seconds
2023-05-29 08:59:40,868 - INFO - Execution time: 0.125 seconds
2023-05-29 09:06:41,489 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:06:58,397 - INFO - Validation time: 2.383 seconds
2023-05-29 09:06:58,421 - INFO - show cart  function triggered!...
2023-05-29 09:06:58,422 - INFO - checking if table exist!!...
2023-05-29 09:06:58,753 - INFO - session closed
2023-05-29 09:06:58,759 - INFO - Validation time: 2.401 seconds
2023-05-29 09:06:58,759 - INFO - Execution time: 2.753 seconds
2023-05-29 09:09:29,548 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:09:41,824 - INFO - Validation time: 2.283 seconds
2023-05-29 09:11:16,413 - INFO - Validation time: 0.165 seconds
2023-05-29 09:11:16,443 - INFO - show cart  function triggered!...
2023-05-29 09:11:16,445 - INFO - checking if table exist!!...
2023-05-29 09:11:16,685 - INFO - session closed
2023-05-29 09:11:16,697 - INFO - Validation time: 0.178 seconds
2023-05-29 09:11:16,698 - INFO - Execution time: 0.452 seconds
2023-05-29 09:15:36,235 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:15:47,817 - INFO - Validation time: 2.319 seconds
2023-05-29 09:15:47,831 - INFO - show cart  function triggered!...
2023-05-29 09:15:47,831 - INFO - checking if table exist!!...
2023-05-29 09:15:47,933 - INFO - session closed
2023-05-29 09:15:47,933 - ERROR - An exception occurred:list index out of range
2023-05-29 09:15:47,933 - ERROR - list index out of range
2023-05-29 09:15:47,934 - INFO - Validation time: 2.327 seconds
2023-05-29 09:15:47,934 - INFO - Execution time: 2.437 seconds
2023-05-29 09:15:47,937 - ERROR - Exception on /show_with_login [POST]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\apiflask\app.py", line 460, in make_response
    return super().make_response(rv)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2138, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'show_from_cart_with_login' did not return a valid response. The function either returned None or ended without a return statement.
2023-05-29 09:22:25,179 - INFO - Serving on http://0.0.0.0:5008
2023-05-29 09:22:44,001 - INFO - Validation time: 2.307 seconds
2023-05-29 09:26:37,662 - INFO - Validation time: 2.281 seconds
2023-05-29 09:26:37,685 - INFO - show cart  function triggered!...
2023-05-29 09:26:37,687 - INFO - checking if table exist!!...
2023-05-29 09:26:37,856 - INFO - session closed
2023-05-29 09:26:37,860 - INFO - Validation time: 2.289 seconds
2023-05-29 09:26:37,860 - INFO - Execution time: 2.482 seconds
